<#
.SYNOPSIS
    GUI tool for creating a GPO to deploy Velociraptor for forensic analysis

.DESCRIPTION
    This script provides a Windows Forms GUI to create and configure a Group Policy Object
    that deploys the Velociraptor digital forensics and incident response agent to Windows
    machines. Evidence is automatically saved to a network share.

.NOTES
    Author: V-Rex GPO Deployment Tool
    Version: 1.0
    Requires:
    - PowerShell 5.1 or later
    - GroupPolicy PowerShell module
    - Administrative privileges
    - Active Directory environment
#>

#Requires -Version 5.1
#Requires -Modules GroupPolicy
#Requires -RunAsAdministrator

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Global variables
$script:LogFile = "$env:TEMP\VelociraptorGPODeployment.log"

# Logging function
function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('Info', 'Warning', 'Error', 'Success')]
        [string]$Level = 'Info'
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    Add-Content -Path $script:LogFile -Value $logMessage

    # Also write to output textbox if available
    if ($script:outputTextBox) {
        $color = switch ($Level) {
            'Error' { [System.Drawing.Color]::Red }
            'Warning' { [System.Drawing.Color]::Orange }
            'Success' { [System.Drawing.Color]::Green }
            default { [System.Drawing.Color]::Black }
        }

        $script:outputTextBox.SelectionStart = $script:outputTextBox.TextLength
        $script:outputTextBox.SelectionLength = 0
        $script:outputTextBox.SelectionColor = $color
        $script:outputTextBox.AppendText("$logMessage`r`n")
        $script:outputTextBox.SelectionColor = $script:outputTextBox.ForeColor
        $script:outputTextBox.ScrollToCaret()
    }
}

# Function to create Velociraptor client configuration
function New-VelociraptorConfig {
    param(
        [string]$ServerUrl,
        [string]$NetworkShare,
        [string]$ConfigPath
    )

    $config = @"
Client:
  server_urls:
    - $ServerUrl

  # Output directory for collected artifacts
  output_directory: $NetworkShare\%COMPUTERNAME%

  # Local buffer directory
  local_buffer:
    memory_size: 50000000
    disk_size: 1000000000
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $env:TEMP\Velociraptor_Buffer.bin
    filename_darwin: /tmp/Velociraptor_Buffer.bin

  # Writeback file for client state
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $env:ProgramData\Velociraptor\velociraptor.writeback.yaml

  # Maximum upload size
  max_upload_size: 10485760

  # Ensure we can write to network share
  windows_installer:
    service_name: Velociraptor
    install_path: $env:ProgramFiles\Velociraptor
    service_description: Velociraptor forensic agent

Logging:
  output_directory: $NetworkShare\%COMPUTERNAME%\Logs
  separate_logs_per_component: true

autoexec:
  argv:
    - artifacts
    - collect
    - "-v"
    - Windows.KapeFiles.Targets
"@

    try {
        $config | Out-File -FilePath $ConfigPath -Encoding UTF8 -Force
        Write-Log "Created Velociraptor configuration at $ConfigPath" -Level Success
        return $true
    }
    catch {
        Write-Log "Failed to create Velociraptor configuration: $($_.Exception.Message)" -Level Error
        return $false
    }
}

# Function to create the deployment script
function New-DeploymentScript {
    param(
        [string]$ScriptPath,
        [string]$VelociraptorMSI,
        [string]$ConfigFile,
        [string]$NetworkShare
    )

    $deployScript = @"
# Velociraptor Deployment Script
# Auto-generated by V-Rex GPO Deployment Tool

`$ErrorActionPreference = 'Stop'
`$LogFile = "$NetworkShare\Deployment\`$env:COMPUTERNAME-deployment.log"

function Write-DeployLog {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path `$LogFile -Value "[`$timestamp] `$Message" -ErrorAction SilentlyContinue
}

try {
    Write-DeployLog "Starting Velociraptor deployment on `$env:COMPUTERNAME"

    # Create local directories
    `$installDir = "`$env:ProgramFiles\Velociraptor"
    `$configDir = "`$env:ProgramData\Velociraptor"

    if (!(Test-Path `$installDir)) {
        New-Item -Path `$installDir -ItemType Directory -Force | Out-Null
        Write-DeployLog "Created installation directory: `$installDir"
    }

    if (!(Test-Path `$configDir)) {
        New-Item -Path `$configDir -ItemType Directory -Force | Out-Null
        Write-DeployLog "Created configuration directory: `$configDir"
    }

    # Copy configuration file
    Copy-Item -Path "$ConfigFile" -Destination "`$configDir\client.config.yaml" -Force
    Write-DeployLog "Copied configuration file"

    # Check if Velociraptor is already installed
    `$service = Get-Service -Name "Velociraptor" -ErrorAction SilentlyContinue

    if (`$service) {
        Write-DeployLog "Velociraptor service already exists. Checking version..."
        # You can add version checking logic here
    }
    else {
        Write-DeployLog "Installing Velociraptor from $VelociraptorMSI"

        # Install MSI silently
        `$arguments = "/i `"$VelociraptorMSI`" /quiet /norestart /log `"$NetworkShare\Deployment\`$env:COMPUTERNAME-install.log`""
        `$process = Start-Process -FilePath "msiexec.exe" -ArgumentList `$arguments -Wait -PassThru

        if (`$process.ExitCode -eq 0) {
            Write-DeployLog "Velociraptor installed successfully"
        }
        else {
            Write-DeployLog "ERROR: Installation failed with exit code `$(`$process.ExitCode)"
            exit `$process.ExitCode
        }
    }

    # Ensure network share directory exists for this computer
    `$computerShare = "$NetworkShare\`$env:COMPUTERNAME"
    if (!(Test-Path `$computerShare)) {
        New-Item -Path `$computerShare -ItemType Directory -Force | Out-Null
        Write-DeployLog "Created computer-specific evidence directory"
    }

    # Start the service if not running
    `$service = Get-Service -Name "Velociraptor" -ErrorAction SilentlyContinue
    if (`$service -and `$service.Status -ne 'Running') {
        Start-Service -Name "Velociraptor"
        Write-DeployLog "Started Velociraptor service"
    }

    Write-DeployLog "Velociraptor deployment completed successfully"
}
catch {
    Write-DeployLog "ERROR: `$(`$_.Exception.Message)"
    exit 1
}
"@

    try {
        $deployScript | Out-File -FilePath $ScriptPath -Encoding UTF8 -Force
        Write-Log "Created deployment script at $ScriptPath" -Level Success
        return $true
    }
    catch {
        Write-Log "Failed to create deployment script: $($_.Exception.Message)" -Level Error
        return $false
    }
}

# Function to create and configure GPO
function New-VelociraptorGPO {
    param(
        [string]$GPOName,
        [string]$VelociraptorMSI,
        [string]$ServerUrl,
        [string]$NetworkShare,
        [string]$TargetOU,
        [string]$DeploymentMethod
    )

    try {
        Write-Log "Starting GPO creation process..." -Level Info

        # Validate inputs
        if (!(Test-Path $VelociraptorMSI)) {
            throw "Velociraptor MSI file not found: $VelociraptorMSI"
        }

        # Test network share access
        if (!(Test-Path $NetworkShare)) {
            Write-Log "Creating network share directory: $NetworkShare" -Level Warning
            New-Item -Path $NetworkShare -ItemType Directory -Force | Out-Null
        }

        # Create subdirectories in network share
        $deploymentDir = Join-Path $NetworkShare "Deployment"
        $configDir = Join-Path $NetworkShare "Config"

        foreach ($dir in @($deploymentDir, $configDir)) {
            if (!(Test-Path $dir)) {
                New-Item -Path $dir -ItemType Directory -Force | Out-Null
                Write-Log "Created directory: $dir" -Level Info
            }
        }

        # Create Velociraptor configuration
        $configFile = Join-Path $configDir "client.config.yaml"
        if (!(New-VelociraptorConfig -ServerUrl $ServerUrl -NetworkShare $NetworkShare -ConfigPath $configFile)) {
            throw "Failed to create Velociraptor configuration"
        }

        # Create deployment script
        $scriptFile = Join-Path $deploymentDir "Deploy-Velociraptor.ps1"
        if (!(New-DeploymentScript -ScriptPath $scriptFile -VelociraptorMSI $VelociraptorMSI -ConfigFile $configFile -NetworkShare $NetworkShare)) {
            throw "Failed to create deployment script"
        }

        # Check if GPO already exists
        $existingGPO = Get-GPO -Name $GPOName -ErrorAction SilentlyContinue
        if ($existingGPO) {
            $result = [System.Windows.Forms.MessageBox]::Show(
                "GPO '$GPOName' already exists. Do you want to overwrite it?",
                "GPO Exists",
                [System.Windows.Forms.MessageBoxButtons]::YesNo,
                [System.Windows.Forms.MessageBoxIcon]::Question
            )

            if ($result -eq [System.Windows.Forms.DialogResult]::No) {
                Write-Log "Operation cancelled by user" -Level Warning
                return $false
            }

            Write-Log "Using existing GPO: $GPOName" -Level Info
            $gpo = $existingGPO
        }
        else {
            # Create new GPO
            Write-Log "Creating new GPO: $GPOName" -Level Info
            $gpo = New-GPO -Name $GPOName -Comment "Velociraptor Forensic Agent Deployment - Created by V-Rex Tool"
            Write-Log "GPO created successfully: $($gpo.DisplayName)" -Level Success
        }

        # Configure GPO based on deployment method
        if ($DeploymentMethod -eq "Startup Script") {
            # Add startup script to GPO
            Write-Log "Configuring GPO with startup script..." -Level Info

            # Get the GPO path
            $gpoPath = "\\$env:USERDNSDOMAIN\SYSVOL\$env:USERDNSDOMAIN\Policies\{$($gpo.Id)}\Machine\Scripts\Startup"

            # Create the scripts directory if it doesn't exist
            if (!(Test-Path $gpoPath)) {
                New-Item -Path $gpoPath -ItemType Directory -Force | Out-Null
            }

            # Copy script to GPO path
            Copy-Item -Path $scriptFile -Destination $gpoPath -Force

            # Set the startup script using registry
            $key = "Software\Policies\Microsoft\Windows\System\Scripts\Startup\0"
            Set-GPRegistryValue -Name $GPOName -Key "HKLM\$key" -ValueName "Script" -Type String -Value "Deploy-Velociraptor.ps1"
            Set-GPRegistryValue -Name $GPOName -Key "HKLM\$key" -ValueName "Parameters" -Type String -Value ""
            Set-GPRegistryValue -Name $GPOName -Key "HKLM\$key" -ValueName "IsPowershell" -Type DWord -Value 1
            Set-GPRegistryValue -Name $GPOName -Key "HKLM\$key" -ValueName "ExecTime" -Type QWord -Value 0

            Write-Log "Startup script configured successfully" -Level Success
        }
        else {
            # Software Installation method
            Write-Log "Configuring GPO with software installation policy..." -Level Info

            # Copy MSI to a shared location accessible by all computers
            $gpoSoftwarePath = Join-Path $NetworkShare "Software"
            if (!(Test-Path $gpoSoftwarePath)) {
                New-Item -Path $gpoSoftwarePath -ItemType Directory -Force | Out-Null
            }

            $sharedMSI = Join-Path $gpoSoftwarePath (Split-Path $VelociraptorMSI -Leaf)
            Copy-Item -Path $VelociraptorMSI -Destination $sharedMSI -Force
            Write-Log "Copied MSI to shared location: $sharedMSI" -Level Info

            # Note: Software Installation via GPO requires GUI/COM objects which are complex in PowerShell
            # Instead, we'll use a startup script that handles the installation
            Write-Log "Note: Using startup script method for MSI deployment" -Level Warning
        }

        # Configure additional GPO settings
        Write-Log "Configuring additional GPO settings..." -Level Info

        # Enable PowerShell script execution if needed
        Set-GPRegistryValue -Name $GPOName -Key "HKLM\Software\Policies\Microsoft\Windows\PowerShell" `
            -ValueName "EnableScripts" -Type DWord -Value 1
        Set-GPRegistryValue -Name $GPOName -Key "HKLM\Software\Policies\Microsoft\Windows\PowerShell" `
            -ValueName "ExecutionPolicy" -Type String -Value "RemoteSigned"

        # Link GPO to OU if specified
        if ($TargetOU) {
            Write-Log "Linking GPO to OU: $TargetOU" -Level Info
            try {
                # Check if link already exists
                $existingLink = Get-GPInheritance -Target $TargetOU |
                    Select-Object -ExpandProperty GpoLinks |
                    Where-Object { $_.DisplayName -eq $GPOName }

                if (!$existingLink) {
                    New-GPLink -Name $GPOName -Target $TargetOU -LinkEnabled Yes
                    Write-Log "GPO linked successfully to $TargetOU" -Level Success
                }
                else {
                    Write-Log "GPO already linked to $TargetOU" -Level Info
                }
            }
            catch {
                Write-Log "Failed to link GPO to OU: $($_.Exception.Message)" -Level Error
            }
        }

        Write-Log "GPO creation and configuration completed successfully!" -Level Success
        Write-Log "GPO Name: $GPOName" -Level Info
        Write-Log "GPO ID: $($gpo.Id)" -Level Info
        Write-Log "Configuration file: $configFile" -Level Info
        Write-Log "Deployment script: $scriptFile" -Level Info
        Write-Log "Evidence will be stored in: $NetworkShare\<ComputerName>" -Level Info

        [System.Windows.Forms.MessageBox]::Show(
            "GPO created successfully!`n`nGPO Name: $GPOName`nGPO ID: $($gpo.Id)`n`nEvidence will be saved to: $NetworkShare\<ComputerName>",
            "Success",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Information
        )

        return $true
    }
    catch {
        Write-Log "Error creating GPO: $($_.Exception.Message)" -Level Error
        [System.Windows.Forms.MessageBox]::Show(
            "Failed to create GPO: $($_.Exception.Message)",
            "Error",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        )
        return $false
    }
}

# Function to browse for file
function Get-FilePath {
    param([string]$Filter = "MSI Files (*.msi)|*.msi|All Files (*.*)|*.*")

    $openFileDialog = New-Object System.Windows.Forms.OpenFileDialog
    $openFileDialog.Filter = $Filter
    $openFileDialog.Title = "Select Velociraptor MSI"

    if ($openFileDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
        return $openFileDialog.FileName
    }
    return $null
}

# Function to browse for folder
function Get-FolderPath {
    param([string]$Description = "Select Network Share for Evidence Storage")

    $folderBrowser = New-Object System.Windows.Forms.FolderBrowserDialog
    $folderBrowser.Description = $Description
    $folderBrowser.ShowNewFolderButton = $true

    if ($folderBrowser.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
        return $folderBrowser.SelectedPath
    }
    return $null
}

# Function to get all OUs
function Get-OrganizationalUnits {
    try {
        Import-Module ActiveDirectory -ErrorAction Stop
        $ous = Get-ADOrganizationalUnit -Filter * | Select-Object -ExpandProperty DistinguishedName | Sort-Object
        return $ous
    }
    catch {
        Write-Log "Failed to retrieve OUs: $($_.Exception.Message)" -Level Warning
        return @()
    }
}

# Create the main form
function Show-MainForm {
    $form = New-Object System.Windows.Forms.Form
    $form.Text = "V-Rex: Velociraptor GPO Deployment Tool"
    $form.Size = New-Object System.Drawing.Size(800, 700)
    $form.StartPosition = "CenterScreen"
    $form.FormBorderStyle = "FixedDialog"
    $form.MaximizeBox = $false
    $form.Icon = [System.Drawing.SystemIcons]::Shield

    # Header Label
    $headerLabel = New-Object System.Windows.Forms.Label
    $headerLabel.Location = New-Object System.Drawing.Point(10, 10)
    $headerLabel.Size = New-Object System.Drawing.Size(760, 40)
    $headerLabel.Text = "Deploy Velociraptor Forensic Agent via Group Policy"
    $headerLabel.Font = New-Object System.Drawing.Font("Segoe UI", 14, [System.Drawing.FontStyle]::Bold)
    $headerLabel.ForeColor = [System.Drawing.Color]::DarkBlue
    $form.Controls.Add($headerLabel)

    # GPO Name
    $gpoNameLabel = New-Object System.Windows.Forms.Label
    $gpoNameLabel.Location = New-Object System.Drawing.Point(10, 60)
    $gpoNameLabel.Size = New-Object System.Drawing.Size(150, 20)
    $gpoNameLabel.Text = "GPO Name:"
    $form.Controls.Add($gpoNameLabel)

    $gpoNameTextBox = New-Object System.Windows.Forms.TextBox
    $gpoNameTextBox.Location = New-Object System.Drawing.Point(170, 58)
    $gpoNameTextBox.Size = New-Object System.Drawing.Size(600, 20)
    $gpoNameTextBox.Text = "Deploy-Velociraptor-Forensics"
    $form.Controls.Add($gpoNameTextBox)

    # Velociraptor MSI Path
    $msiLabel = New-Object System.Windows.Forms.Label
    $msiLabel.Location = New-Object System.Drawing.Point(10, 90)
    $msiLabel.Size = New-Object System.Drawing.Size(150, 20)
    $msiLabel.Text = "Velociraptor MSI:"
    $form.Controls.Add($msiLabel)

    $msiTextBox = New-Object System.Windows.Forms.TextBox
    $msiTextBox.Location = New-Object System.Drawing.Point(170, 88)
    $msiTextBox.Size = New-Object System.Drawing.Size(520, 20)
    $form.Controls.Add($msiTextBox)

    $msiBrowseButton = New-Object System.Windows.Forms.Button
    $msiBrowseButton.Location = New-Object System.Drawing.Point(700, 86)
    $msiBrowseButton.Size = New-Object System.Drawing.Size(70, 24)
    $msiBrowseButton.Text = "Browse..."
    $msiBrowseButton.Add_Click({
        $path = Get-FilePath
        if ($path) { $msiTextBox.Text = $path }
    })
    $form.Controls.Add($msiBrowseButton)

    # Velociraptor Server URL
    $serverLabel = New-Object System.Windows.Forms.Label
    $serverLabel.Location = New-Object System.Drawing.Point(10, 120)
    $serverLabel.Size = New-Object System.Drawing.Size(150, 20)
    $serverLabel.Text = "Server URL:"
    $form.Controls.Add($serverLabel)

    $serverTextBox = New-Object System.Windows.Forms.TextBox
    $serverTextBox.Location = New-Object System.Drawing.Point(170, 118)
    $serverTextBox.Size = New-Object System.Drawing.Size(600, 20)
    $serverTextBox.Text = "https://velociraptor.domain.local:8000"
    $form.Controls.Add($serverTextBox)

    # Network Share Path
    $shareLabel = New-Object System.Windows.Forms.Label
    $shareLabel.Location = New-Object System.Drawing.Point(10, 150)
    $shareLabel.Size = New-Object System.Drawing.Size(150, 20)
    $shareLabel.Text = "Network Share:"
    $form.Controls.Add($shareLabel)

    $shareTextBox = New-Object System.Windows.Forms.TextBox
    $shareTextBox.Location = New-Object System.Drawing.Point(170, 148)
    $shareTextBox.Size = New-Object System.Drawing.Size(520, 20)
    $shareTextBox.Text = "\\server\VelociraptorEvidence"
    $form.Controls.Add($shareTextBox)

    $shareBrowseButton = New-Object System.Windows.Forms.Button
    $shareBrowseButton.Location = New-Object System.Drawing.Point(700, 146)
    $shareBrowseButton.Size = New-Object System.Drawing.Size(70, 24)
    $shareBrowseButton.Text = "Browse..."
    $shareBrowseButton.Add_Click({
        $path = Get-FolderPath
        if ($path) { $shareTextBox.Text = $path }
    })
    $form.Controls.Add($shareBrowseButton)

    # Target OU
    $ouLabel = New-Object System.Windows.Forms.Label
    $ouLabel.Location = New-Object System.Drawing.Point(10, 180)
    $ouLabel.Size = New-Object System.Drawing.Size(150, 20)
    $ouLabel.Text = "Target OU (optional):"
    $form.Controls.Add($ouLabel)

    $ouComboBox = New-Object System.Windows.Forms.ComboBox
    $ouComboBox.Location = New-Object System.Drawing.Point(170, 178)
    $ouComboBox.Size = New-Object System.Drawing.Size(520, 20)
    $ouComboBox.DropDownStyle = "DropDown"
    $form.Controls.Add($ouComboBox)

    $ouRefreshButton = New-Object System.Windows.Forms.Button
    $ouRefreshButton.Location = New-Object System.Drawing.Point(700, 176)
    $ouRefreshButton.Size = New-Object System.Drawing.Size(70, 24)
    $ouRefreshButton.Text = "Refresh"
    $ouRefreshButton.Add_Click({
        $ouComboBox.Items.Clear()
        $ous = Get-OrganizationalUnits
        foreach ($ou in $ous) {
            $ouComboBox.Items.Add($ou)
        }
    })
    $form.Controls.Add($ouRefreshButton)

    # Deployment Method
    $methodLabel = New-Object System.Windows.Forms.Label
    $methodLabel.Location = New-Object System.Drawing.Point(10, 210)
    $methodLabel.Size = New-Object System.Drawing.Size(150, 20)
    $methodLabel.Text = "Deployment Method:"
    $form.Controls.Add($methodLabel)

    $methodComboBox = New-Object System.Windows.Forms.ComboBox
    $methodComboBox.Location = New-Object System.Drawing.Point(170, 208)
    $methodComboBox.Size = New-Object System.Drawing.Size(600, 20)
    $methodComboBox.DropDownStyle = "DropDownList"
    $methodComboBox.Items.AddRange(@("Startup Script", "Software Installation"))
    $methodComboBox.SelectedIndex = 0
    $form.Controls.Add($methodComboBox)

    # Output TextBox
    $outputLabel = New-Object System.Windows.Forms.Label
    $outputLabel.Location = New-Object System.Drawing.Point(10, 240)
    $outputLabel.Size = New-Object System.Drawing.Size(150, 20)
    $outputLabel.Text = "Output Log:"
    $form.Controls.Add($outputLabel)

    $script:outputTextBox = New-Object System.Windows.Forms.RichTextBox
    $script:outputTextBox.Location = New-Object System.Drawing.Point(10, 265)
    $script:outputTextBox.Size = New-Object System.Drawing.Size(760, 330)
    $script:outputTextBox.ReadOnly = $true
    $script:outputTextBox.Font = New-Object System.Drawing.Font("Consolas", 9)
    $script:outputTextBox.BackColor = [System.Drawing.Color]::Black
    $script:outputTextBox.ForeColor = [System.Drawing.Color]::Lime
    $form.Controls.Add($script:outputTextBox)

    # Create GPO Button
    $createButton = New-Object System.Windows.Forms.Button
    $createButton.Location = New-Object System.Drawing.Point(550, 605)
    $createButton.Size = New-Object System.Drawing.Size(100, 30)
    $createButton.Text = "Create GPO"
    $createButton.BackColor = [System.Drawing.Color]::Green
    $createButton.ForeColor = [System.Drawing.Color]::White
    $createButton.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Bold)
    $createButton.Add_Click({
        # Validate inputs
        if ([string]::IsNullOrWhiteSpace($gpoNameTextBox.Text)) {
            [System.Windows.Forms.MessageBox]::Show("Please enter a GPO name.", "Validation Error",
                [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Warning)
            return
        }

        if ([string]::IsNullOrWhiteSpace($msiTextBox.Text)) {
            [System.Windows.Forms.MessageBox]::Show("Please select a Velociraptor MSI file.", "Validation Error",
                [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Warning)
            return
        }

        if ([string]::IsNullOrWhiteSpace($serverTextBox.Text)) {
            [System.Windows.Forms.MessageBox]::Show("Please enter the Velociraptor server URL.", "Validation Error",
                [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Warning)
            return
        }

        if ([string]::IsNullOrWhiteSpace($shareTextBox.Text)) {
            [System.Windows.Forms.MessageBox]::Show("Please enter a network share path.", "Validation Error",
                [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Warning)
            return
        }

        $script:outputTextBox.Clear()
        Write-Log "=== Starting Velociraptor GPO Deployment ===" -Level Info

        New-VelociraptorGPO -GPOName $gpoNameTextBox.Text `
            -VelociraptorMSI $msiTextBox.Text `
            -ServerUrl $serverTextBox.Text `
            -NetworkShare $shareTextBox.Text `
            -TargetOU $ouComboBox.Text `
            -DeploymentMethod $methodComboBox.SelectedItem
    })
    $form.Controls.Add($createButton)

    # Close Button
    $closeButton = New-Object System.Windows.Forms.Button
    $closeButton.Location = New-Object System.Drawing.Point(660, 605)
    $closeButton.Size = New-Object System.Drawing.Size(100, 30)
    $closeButton.Text = "Close"
    $closeButton.Add_Click({ $form.Close() })
    $form.Controls.Add($closeButton)

    # Show initial log message
    Write-Log "V-Rex Velociraptor GPO Deployment Tool initialized" -Level Info
    Write-Log "Log file: $script:LogFile" -Level Info
    Write-Log "Ready to create GPO..." -Level Success

    # Show the form
    $form.Add_Shown({$form.Activate()})
    [void]$form.ShowDialog()
}

# Main execution
try {
    # Check for required modules
    if (!(Get-Module -ListAvailable -Name GroupPolicy)) {
        [System.Windows.Forms.MessageBox]::Show(
            "GroupPolicy PowerShell module is not available. Please install RSAT tools.",
            "Missing Module",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        )
        exit 1
    }

    # Import required modules
    Import-Module GroupPolicy -ErrorAction Stop

    # Show the main form
    Show-MainForm
}
catch {
    [System.Windows.Forms.MessageBox]::Show(
        "Fatal error: $($_.Exception.Message)",
        "Error",
        [System.Windows.Forms.MessageBoxButtons]::OK,
        [System.Windows.Forms.MessageBoxIcon]::Error
    )
    exit 1
}
